import type { Metadata } from "next";
import "./globals.css";
import "../styles.css";

import Home from "./page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Ginto" }}>
        <Home />
        {children}
      </body>
    </html>
  );
}
